trigger:

  branches:
      include:
      - main
      - env-dev
      - env-qa
      - env-prod
      

  tags:
    exclude:
    - do_not_build

  paths:
    exclude:
    - README.md

resources:
  repositories:
  # template repository
  - repository: PipelineComman1
    type: git
    name: PipelineComman1

# variables:
# - group: Snowflake.Database
# # - name: DBNAME
# #   value: flyway_demo 
# - name: DBNAME
#   value: TEST
# - name: flywayartifactName
#   value: DatabaseArtifacts  
# - name: flywayVmImage
#   value: 'ubuntu-latest'  
# - name: flywayContainerImage
#   value: 'kulmam92/flyway-azure:6.2.3'  

variables:
- group: Snowflake.Database
# - name: DBNAME
#   value: flyway_demo 
- name: DBNAME
  value: TEST
- name: flywayartifactName
  value: DatabaseArtifacts  
- name: flywayVmImage
  value: 'flyagent' 
  

stages:
- stage: Build12
  variables:
  - name: DBNAME_POSTFIX
    value: _DEV
  jobs:
  - template: templates/YAMLpipelines/snowflakeFlywayBuild.yml@PipelineComman1
    parameters:
      jobName: 'BuildDatabase'
      databaseName: $(DBNAME)
      databasePostfix: $(DBNAME_POSTFIX)
      artifactName: $(flywayartifactName)
      vmImage: $(flywayVmImage)
      #containerImage: $(flywayContainerImage)


#DEV Stage
- stage: DEV
  condition: and(succeeded('Build12'), eq(variables['Build.SourceBranch'], 'refs/heads/env-dev'))
  variables:
  - name: DBNAME_POSTFIX
    value: _DEV
  jobs:
  - template: templates/YAMLpipelines/snowflakeFlywayDeploy.yml@PipelineComman1
    parameters:
      jobName: DEV
      databaseName: $(DBNAME)
      databasePostfix: $(DBNAME_POSTFIX)
      artifactName: $(flywayartifactName)
      vmImage: $(flywayVmImage)
      #containerImage: $(flywayContainerImage)
      environmentName: DEV


##QA Stage
- stage: QA
  condition: and(succeeded('Build12'), eq(variables['Build.SourceBranch'], 'refs/heads/env-qa'))
  variables:
  - name: DBNAME_POSTFIX
    value: _QA
  jobs:
  - template: templates/YAMLpipelines/snowflakeFlywayDeploy.yml@PipelineComman1
    parameters:
      jobName: QA
      databaseName: $(DBNAME)
      databasePostfix: $(DBNAME_POSTFIX)
      artifactName: $(flywayartifactName)
      vmImage: $(flywayVmImage)
      #containerImage: $(flywayContainerImage)
      environmentName: QA

##PROD Stage
- stage: PROD
  condition: and(succeeded('Build12'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
  - name: DBNAME_POSTFIX
    value: ''
  jobs:
  - template: templates/YAMLpipelines/snowflakeFlywayDeploy.yml@PipelineComman1
    parameters:
      jobName: PROD
      databaseName: $(DBNAME)
      databasePostfix: $(DBNAME_POSTFIX)
      artifactName: $(flywayartifactName)
      vmImage: $(flywayVmImage)
      #containerImage: $(flywayContainerImage)
      environmentName: PROD